### ISSUE TITLE
Set take off altitude to mission altitude

### ISSUE THREAD

**Issue by BitMapping** [DroidPlanner/Tower#1443]
In survey missions the automatically included take off command has a fixed altitude of 10m. For security reasons (e.g. tree on the way to the first WP) it would be good if the take off altitude would be set to mission altitude.
The problems is that the mission is uploaded immediately and thus this 10m can only be changes if the mission is uploaded again.

**Comment by ne0fhyk** [comment]
Fixed by PR #1467

**Comment by ThorstenDP** [comment]
Hi Fredia,
this problems still exists in 3.1.6 from Apr 25. So your fix should be in there. Can you check it?
Thanks and cheers,
Thorsten
