### ISSUE TITLE
takeoff for planes

### ISSUE THREAD

**Issue by Hasi123** [DroidPlanner/Tower#1515]
It is not possible to set the pitch angle at takeoff. It is currently set to zero, so the airplane will not climb.

**Comment by ne0fhyk** [comment]
Fixed by pr #1595

**Comment by anemostec** [comment]
nope, it is still not working in the 3.2.1 beta version

the pitch parameter is available as a parameter in the takeoff waypoint, but it is erased back to zero as soon a the mission is transfered to the drone.

**Comment by ne0fhyk** [comment]
Fixed by pr https://github.com/dronekit/dronekit-android/pull/427
